export const countries = [
  { code: "AF", name: "Afghanistan", lat: 34.5, lng: 66 },
  { code: "AL", name: "Albania", lat: 41.2, lng: 20 },
  { code: "DZ", name: "Algeria", lat: 28, lng: 3 },
  { code: "AD", name: "Andorra", lat: 42.5, lng: 1.5 },
  { code: "AO", name: "Angola", lat: -12.5, lng: 18.5 },
  { code: "AR", name: "Argentina", lat: -34, lng: -64 },
  { code: "AM", name: "Armenia", lat: 40.1, lng: 45 },
  { code: "AU", name: "Australia", lat: -25, lng: 133 },
  { code: "AT", name: "Austria", lat: 47.5, lng: 14.5 },
  { code: "AZ", name: "Azerbaijan", lat: 40.1, lng: 47.5 },
  { code: "BS", name: "Bahamas", lat: 25, lng: -77 },
  { code: "BH", name: "Bahrain", lat: 26, lng: 50.5 },
  { code: "BD", name: "Bangladesh", lat: 24, lng: 90 },
  { code: "BB", name: "Barbados", lat: 13.2, lng: -59.5 },
  { code: "BY", name: "Belarus", lat: 53.7, lng: 28 },
  { code: "BE", name: "Belgium", lat: 50.5, lng: 4.5 },
  { code: "BZ", name: "Belize", lat: 17.2, lng: -88.5 },
  { code: "BJ", name: "Benin", lat: 9.5, lng: 2.25 },
  { code: "BT", name: "Bhutan", lat: 27.5, lng: 90.5 },
  { code: "BO", name: "Bolivia", lat: -16.3, lng: -64.5 },
  { code: "BA", name: "Bosnia and Herzegovina", lat: 44.2, lng: 17.8 },
  { code: "BW", name: "Botswana", lat: -22, lng: 24 },
  { code: "BR", name: "Brazil", lat: -14, lng: -51 },
  { code: "BN", name: "Brunei", lat: 4.5, lng: 114.7 },
  { code: "BG", name: "Bulgaria", lat: 42.7, lng: 25.5 },
  { code: "BF", name: "Burkina Faso", lat: 12.2, lng: -1.5 },
  { code: "BI", name: "Burundi", lat: -3.3, lng: 30 },
  { code: "KH", name: "Cambodia", lat: 12.5, lng: 105 },
  { code: "CM", name: "Cameroon", lat: 6, lng: 12 },
  { code: "CA", name: "Canada", lat: 56, lng: -106 },
  { code: "CV", name: "Cape Verde", lat: 16, lng: -24 },
  { code: "CF", name: "Central African Republic", lat: 6.6, lng: 20.9 },
  { code: "TD", name: "Chad", lat: 15, lng: 19 },
  { code: "CL", name: "Chile", lat: -35, lng: -71 },
  { code: "CN", name: "China", lat: 35, lng: 103 },
  { code: "CO", name: "Colombia", lat: 4, lng: -72 },
  { code: "KM", name: "Comoros", lat: -11.7, lng: 43.3 },
  { code: "CG", name: "Congo", lat: -1, lng: 15 },
  { code: "CD", name: "Democratic Republic of the Congo", lat: -3, lng: 23 },
  { code: "CR", name: "Costa Rica", lat: 9.7, lng: -84 },
  { code: "HR", name: "Croatia", lat: 45.1, lng: 15.2 },
  { code: "CU", name: "Cuba", lat: 21.5, lng: -80 },
  { code: "CY", name: "Cyprus", lat: 35, lng: 33 },
  { code: "CZ", name: "Czech Republic", lat: 49.8, lng: 15.5 },
  { code: "DK", name: "Denmark", lat: 56, lng: 10 },
  { code: "DJ", name: "Djibouti", lat: 11.8, lng: 42.6 },
  { code: "DO", name: "Dominican Republic", lat: 18.7, lng: -70.2 },
  { code: "EC", name: "Ecuador", lat: -1.8, lng: -78 },
  { code: "EG", name: "Egypt", lat: 26, lng: 30 },
  { code: "SV", name: "El Salvador", lat: 13.8, lng: -88.9 },
  { code: "EE", name: "Estonia", lat: 58.7, lng: 25 },
  { code: "ET", name: "Ethiopia", lat: 9, lng: 40 },
  { code: "FI", name: "Finland", lat: 64, lng: 26 },
  { code: "FR", name: "France", lat: 46, lng: 2 },
  { code: "DE", name: "Germany", lat: 51, lng: 10 },
  { code: "GR", name: "Greece", lat: 39, lng: 22 },
  { code: "GL", name: "Greenland", lat: 72, lng: -40 },
  { code: "GT", name: "Guatemala", lat: 15.8, lng: -90.2 },
  { code: "GN", name: "Guinea", lat: 10.4, lng: -10.9 },
  { code: "HT", name: "Haiti", lat: 19, lng: -72.4 },
  { code: "HN", name: "Honduras", lat: 15, lng: -86.5 },
  { code: "HU", name: "Hungary", lat: 47, lng: 19 },
  { code: "IS", name: "Iceland", lat: 65, lng: -19 },
  { code: "IN", name: "India", lat: 21, lng: 78 },
  { code: "ID", name: "Indonesia", lat: -2, lng: 118 },
  { code: "IR", name: "Iran", lat: 32, lng: 53 },
  { code: "IQ", name: "Iraq", lat: 33, lng: 44 },
  { code: "IE", name: "Ireland", lat: 53, lng: -8 },
  { code: "IL", name: "Israel", lat: 31.5, lng: 34.8 },
  { code: "IT", name: "Italy", lat: 42.5, lng: 12.5 },
  { code: "JM", name: "Jamaica", lat: 18.1, lng: -77.3 },
  { code: "JP", name: "Japan", lat: 36, lng: 138 },
  { code: "JO", name: "Jordan", lat: 31, lng: 36 },
  { code: "KZ", name: "Kazakhstan", lat: 48, lng: 68 },
  { code: "KE", name: "Kenya", lat: 1, lng: 38 },
  { code: "KW", name: "Kuwait", lat: 29.3, lng: 47.5 },
  { code: "KG", name: "Kyrgyzstan", lat: 41, lng: 75 },
  { code: "LA", name: "Laos", lat: 18, lng: 105 },
  { code: "LV", name: "Latvia", lat: 56.9, lng: 24.1 },
  { code: "LB", name: "Lebanon", lat: 33.8, lng: 35.8 },
  { code: "LS", name: "Lesotho", lat: -29.6, lng: 28.2 },
  { code: "LR", name: "Liberia", lat: 6.4, lng: -9.3 },
  { code: "LY", name: "Libya", lat: 26, lng: 17 },
  { code: "LT", name: "Lithuania", lat: 55.2, lng: 23.9 },
  { code: "LU", name: "Luxembourg", lat: 49.8, lng: 6.1 },
  { code: "MG", name: "Madagascar", lat: -18.8, lng: 46.8 },
  { code: "MW", name: "Malawi", lat: -13.2, lng: 34.3 },
  { code: "MY", name: "Malaysia", lat: 4, lng: 102 },
  { code: "MV", name: "Maldives", lat: 3.2, lng: 73 },
  { code: "ML", name: "Mali", lat: 17, lng: -4 },
  { code: "MT", name: "Malta", lat: 35.9, lng: 14.4 },
  { code: "MX", name: "Mexico", lat: 23, lng: -102 },
  { code: "MD", name: "Moldova", lat: 47, lng: 28 },
  { code: "MN", name: "Mongolia", lat: 46, lng: 105 },
  { code: "ME", name: "Montenegro", lat: 42.7, lng: 19.3 },
  { code: "MA", name: "Morocco", lat: 31.7, lng: -7 },
  { code: "MZ", name: "Mozambique", lat: -18.5, lng: 35 },
  { code: "MM", name: "Myanmar", lat: 21, lng: 96 },
  { code: "NA", name: "Namibia", lat: -22, lng: 17 },
  { code: "NP", name: "Nepal", lat: 28, lng: 84 },
  { code: "NL", name: "Netherlands", lat: 52.1, lng: 5.3 },
  { code: "NZ", name: "New Zealand", lat: -41, lng: 174 },
  { code: "NI", name: "Nicaragua", lat: 12.8, lng: -85 },
  { code: "NE", name: "Niger", lat: 17.6, lng: 8 },
  { code: "NG", name: "Nigeria", lat: 9, lng: 8 },
  { code: "KP", name: "North Korea", lat: 40, lng: 127 },
  { code: "NO", name: "Norway", lat: 60, lng: 8 },
  { code: "OM", name: "Oman", lat: 21, lng: 57 },
  { code: "PK", name: "Pakistan", lat: 30, lng: 70 },
  { code: "PA", name: "Panama", lat: 8.5, lng: -80 },
  { code: "PG", name: "Papua New Guinea", lat: -6, lng: 147 },
  { code: "PY", name: "Paraguay", lat: -23, lng: -58 },
  { code: "PE", name: "Peru", lat: -10, lng: -76 },
  { code: "PH", name: "Philippines", lat: 13, lng: 122 },
  { code: "PL", name: "Poland", lat: 52, lng: 19 },
  { code: "PT", name: "Portugal", lat: 39, lng: -8 },
  { code: "QA", name: "Qatar", lat: 25.3, lng: 51.2 },
  { code: "RO", name: "Romania", lat: 45.9, lng: 24.9 },
  { code: "RU", name: "Russia", lat: 61, lng: 105 },
  { code: "RW", name: "Rwanda", lat: -2, lng: 30 },
  { code: "SA", name: "Saudi Arabia", lat: 24, lng: 45 },
  { code: "SN", name: "Senegal", lat: 14, lng: -14 },
  { code: "RS", name: "Serbia", lat: 44, lng: 20 },
  { code: "SG", name: "Singapore", lat: 1.3, lng: 103.8 },
  { code: "SK", name: "Slovakia", lat: 48.7, lng: 19.7 },
  { code: "SI", name: "Slovenia", lat: 46.1, lng: 14.9 },
  { code: "ZA", name: "South Africa", lat: -30, lng: 25 },
  { code: "KR", name: "South Korea", lat: 36, lng: 128 },
  { code: "ES", name: "Spain", lat: 40, lng: -4 },
  { code: "LK", name: "Sri Lanka", lat: 7, lng: 81 },
  { code: "SD", name: "Sudan", lat: 15, lng: 30 },
  { code: "SE", name: "Sweden", lat: 62, lng: 15 },
  { code: "CH", name: "Switzerland", lat: 46.8, lng: 8.2 },
  { code: "SY", name: "Syria", lat: 35, lng: 38 },
  { code: "TW", name: "Taiwan", lat: 23.7, lng: 121 },
  { code: "TJ", name: "Tajikistan", lat: 39, lng: 71 },
  { code: "TZ", name: "Tanzania", lat: -6, lng: 35 },
  { code: "TH", name: "Thailand", lat: 15, lng: 101 },
  { code: "TR", name: "Turkey", lat: 39, lng: 35 },
  { code: "UG", name: "Uganda", lat: 1, lng: 32 },
  { code: "UA", name: "Ukraine", lat: 49, lng: 32 },
  { code: "AE", name: "United Arab Emirates", lat: 24, lng: 54 },
  { code: "GB", name: "United Kingdom", lat: 55, lng: -3 },
  { code: "US", name: "United States", lat: 38, lng: -97 },
  { code: "UY", name: "Uruguay", lat: -32, lng: -55 },
  { code: "UZ", name: "Uzbekistan", lat: 41, lng: 64 },
  { code: "VE", name: "Venezuela", lat: 7, lng: -66 },
  { code: "VN", name: "Vietnam", lat: 16, lng: 108 },
  { code: "YE", name: "Yemen", lat: 15, lng: 48 },
  { code: "ZM", name: "Zambia", lat: -13, lng: 27 },
  { code: "ZW", name: "Zimbabwe", lat: -19, lng: 29 }
];
